# Generated by Django 6.0.7 on 2026-08-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_learner_alter_payment_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
