# Generated by Django 6.0.8 on 2026-08-08 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['category_name'], 'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.RenameField(
            model_name='skillcategory',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='skill',
            name='demand_level',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-layer-group', help_text='FontAwesome icon class', max_length=80),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('offered', 'Offered'), ('wanted', 'Wanted')], default='offered', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(help_text='User who owns this skill listing', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
