# Generated by Django 6.0.8 on 2026-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('meeting_id', models.CharField(max_length=100)),
                ('meeting_link', models.URLField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
