# Generated by Django 6.0.8 on 2026-08-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_videosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='file',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='videosession',
            name='status',
        ),
        migrations.AddField(
            model_name='videosession',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.booking'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
