# Generated by Django 6.0.8 on 2026-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('skills', models.TextField()),
                ('notifications', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
