# Generated by Django 6.0.8 on 2026-08-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otpverification',
            table=None,
        ),
    ]
