# Generated by Django 6.0.7 on 2026-08-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_booking_session_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doubt',
            name='student_name',
            field=models.CharField(default='Student', max_length=100),
        ),
        migrations.AddField(
            model_name='doubt',
            name='title',
            field=models.CharField(default='General Doubt', max_length=200),
        ),
    ]
