# Generated by Django 6.0.8 on 2026-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('skill_request', 'Skill Swap Request'), ('system', 'System Notification'), ('message', 'Direct Message'), ('achievement', 'Skill Achievement'), ('booking', 'Booking Update')], default='system', max_length=30),
        ),
    ]
